### ISSUE TITLE
Chunk uploading error

### ISSUE THREAD

**Issue by johangit** [pionl/laravel-chunk-upload#108]
I use your code example for saving chunks.
When I use resumable.js sometimes one of the POST requests returns 500 error.

```
RuntimeException: SplFileInfo::getType(): Lstat failed for  <chunk_file_path> in file /Users/johan/web/upwork/file_uploader/app/vendor/league/flysystem/src/Adapter/Local.php on line 508
```

If I trying to "Reply XHR" via Google chrome console - it returns 200 OK.

The problem is not permanent, it happens periodically.

Resumable.js allows you to retry failed requests and the problem can be ignored. But I still do not understand why this is happening and what does it depend on? Perhaps the problem is in the hardware?

I added try/catch for getting more info about chunk file:
```
    public function upload(Request $request, FileReceiver $receiver)
    {
        Log::info($_FILES);
        $isUploaded = is_uploaded_file($_FILES['file']['tmp_name']);
        Log::info('is_uploaded_file: ' . ($isUploaded ? 'true' : 'false'));
        copy($_FILES['file']['tmp_name'], storage_path('app/chunk_copies' . $_FILES['file']['tmp_name']));

        try {

        // code from example

        } catch (\Exception $e) {
            Log::info('chunk uploading error');
            Log::info($e->getMessage());
            abort(500);
        }

        return response()->json([
            'done' => $handler->getPercentageDone()
        ]);
    }
```

It returns the next info:
```
[2020-07-24 15:12:15] local.INFO: is_uploaded_file: true  
[2020-07-24 15:12:15] local.INFO: array (
  'file' => 
  array (
    'name' => 'electrum-3.3.8.dmg',
    'type' => 'application/octet-stream',
    'tmp_name' => '/private/var/tmp/phpnQolJ4',
    'error' => 0,
    'size' => 3145728,
  ),
)  
```
So the chunk file exists and not zero file size.

Any ideas why it happens?

**Comment by rbsl-yasmin** [comment]
+1

**Comment by sbeus** [comment]
+1

**Comment by kartikkapatel** [comment]
+1

**Comment by pionl** [comment]
Do you have exception message, code line?

**Comment by sbeus** [comment]
Here's the [partial] stack trace as captured by Sentry:

```
RuntimeException: SplFileInfo::getType(): Lstat failed for [...]-Zp7l1tlwKc2Imhgt9wBTtTtcXDVtFxfYUdlrKq4u-8e16bb64-5e71-4770-b175-88b299da8a96.54.part
#64 /vendor/league/flysystem/src/Adapter/Local.php(509): SplFileInfo::getType
#63 /vendor/league/flysystem/src/Adapter/Local.php(509): League\Flysystem\Adapter\Local::mapFileInfo
#62 /vendor/league/flysystem/src/Adapter/Local.php(452): League\Flysystem\Adapter\Local::normalizeFileInfo
#61 /vendor/league/flysystem/src/Adapter/Local.php(288): League\Flysystem\Adapter\Local::listContents
#60 /vendor/league/flysystem/src/Filesystem.php(272): League\Flysystem\Filesystem::listContents
#59 /vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(654): Illuminate\Filesystem\FilesystemAdapter::files
#58 /vendor/pion/laravel-chunk-upload/src/Storage/ChunkStorage.php(118): Pion\Laravel\ChunkUpload\Storage\ChunkStorage::files
#57 /vendor/pion/laravel-chunk-upload/src/Save/ParallelSave.php(100): Pion\Laravel\ChunkUpload\Save\ParallelSave::getSavedChunksFiles
#56 /vendor/pion/laravel-chunk-upload/src/Save/ParallelSave.php(77): Pion\Laravel\ChunkUpload\Save\ParallelSave::handleChunkFile
#55 /vendor/pion/laravel-chunk-upload/src/Save/ChunkSave.php(157): Pion\Laravel\ChunkUpload\Save\ChunkSave::handleChunk
#54 /vendor/pion/laravel-chunk-upload/src/Save/ChunkSave.php(67): Pion\Laravel\ChunkUpload\Save\ChunkSave::__construct
#53 /vendor/pion/laravel-chunk-upload/src/Save/ParallelSave.php(55): Pion\Laravel\ChunkUpload\Save\ParallelSave::__construct
#52 /vendor/pion/laravel-chunk-upload/src/Handler/Traits/HandleParallelUploadTrait.php(34): Pion\Laravel\ChunkUpload\Handler\DropZoneUploadHandler::startSaving
#51 /vendor/pion/laravel-chunk-upload/src/Receiver/FileReceiver.php(100): Pion\Laravel\ChunkUpload\Receiver\FileReceiver::receive
...
```

**Comment by johangit** [comment]
> Do you have exception message, code line?

Sorry, not. During these two years I changed my laptop and finished the project. 
So I can't reproduce the issue now.

**Comment by sbeus** [comment]
@pionl, the full file name of the most recent example is:

```
/dap/portal/app/chunks/evwatts.analysis.Q4_2021_EVWatts_Analysis_CSVs.zip-Zp7l1tlwKc2Imhgt9wBTtTtcXDVtFxfYUdlrKq4u-8e16bb64-5e71-4770-b175-88b299da8a96.54.part
```

And the PHP version is 7.4.26 but this has been happening for a long time with earlier PHP versions also.

And I should point out that trying again often works, so I don't know that the path length could be an issue.

**Comment by pionl** [comment]
I would assume that there is probably issue of parallel saves and reading the contents of chunks to determine if the upload has finished. 

Did not found many info on the error but it seems that the process is unable to access the file for the moment. Not sure why the file systems wants to get the file content... the logic does not needed the information so it would be "wanted" to probably remove it. 

Laravel 9 uses different library that could resolve the issue.

**Comment by sbeus** [comment]
@pionl, I wondered the same thing about Laravel 9.  As soon as I can get the server's PHP bumped to 8.x, I'll upgrade Laravel and see if that fixes it.  Thanks for looking at the issue.

**Comment by soipo** [comment]
@sbeus did you have the same problem with Laravel 9 ?

**Comment by gergo2007** [comment]
any updates on this?

**Comment by dvcsiky** [comment]
@sbeus @soipo it won't be fixed with new Laravel.

The problem relies with the fact that using `DirectoryIterator` (in `Flysystem`, or indeed anywhere else, on non-read-only media) is delusional.

The listing is obtained (see `php-src/ext/spl_directory.c`) by `spl_filesystem_dir_open()` _immediately_, then cached.
So that when someone iterates on the result, it is **guaranteed to be outdated**.
In some cases, this poses no problems.
But with `ParallelSave`, as the name implies, this **can and does** occur even using it alone.

So that whenever iterating over a DirectoryIterator, **any errors _must_ be ignored**, unless it is the very entry you are interested in.

To me, throwing / letting through an exception invariantly on failure within the loop is absolutely unreasonable.

Currently the only solution is to remove Flysystem altogether, and use reasonable plain C wrapper functions (like `opendir()`, `readdir()` etc.) for filesystem access, and checking (and ignoring) errors yourself.

But anyway, for anyone wanting to stick with the (often flawed) "Laravel ways", this problem should be fixed in `Flysystem`, and not here.
