### ISSUE TITLE
Sometimes get 500 error

### ISSUE THREAD

**Issue by rhnkyr** [pionl/laravel-chunk-upload#123]
Hi @pionl,

thanks for this super cool lib. 

This is my dropzone setup 

```
 const cloudZone = new Dropzone("#cloudZone", {
                paramName: 'cloud_file',
                url: "{{route('admin.web-applications.upload')}}",
                autoProcessQueue: true,
                parallelUploads: 3,
                chunking: true,
                retryChunks: true,
                addRemoveLinks: true,
                forceChunking: true,
                parallelChunkUploads: true,
                dictCancelUpload: '{{__('application.cloud_zone.cancel_upload')}}',
                dictCancelUploadConfirmation: '{{__('application.cloud_zone.cancel_upload_confirmation')}}',
                dictRemoveFileConfirmation: '{{__('application.cloud_zone.remove_file_confirmation')}}',
                dictRemoveFile: '{{__('application.cloud_zone.remove_file')}}',
            });
```

With this setup sometimes I get 500 which is :

 ```
"message": "Could not move the file \"/app/storage/app/chunks/./xxxxxxxx.mp4-TaOTGirruUes2wGhdgyZRmE7SSt8Pax3gu6AypSD.part\" to \"/app/storage/app/upload/video-mp4/2021-07-26/xxxxxxxx_8e3b72840194d1e7823e066bd5c493e1.mp4\" (rename(/app/storage/app/chunks/./xxxxxxxx.mp4-TaOTGirruUes2wGhdgyZRmE7SSt8Pax3gu6AypSD.part,/app/storage/app/upload/video-mp4/2021-07-26/xxxxxxxx.mp4): No such file or directory).",
    "exception": "Symfony\\Component\\HttpFoundation\\File\\Exception\\FileException",
    "file": "/app/vendor/symfony/http-foundation/File/File.php",
    "line": 99,
```

But at he end file created / uploaded successfully. Any idea what does it happen?

**Comment by pionl** [comment]
The file path is quite strange, mainly this part `/app/storage/app/chunks/./`. Maybe some kind of different disk settings?

With default local storage it works.

**Comment by khoazero123** [comment]
I have the same issue. Here is my log

```
[2024-01-06 19:57:47] local.ERROR: The file "/var/www/html/storage/app/chunks/./video.mp4-qFeNHvW30h7B8ZtqHmXWEgaYrc2r3gvTuyTGkcIU.part" does not exist {"exception":"[object] (Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException(code: 0): The file \"/var/www/html/storage/app/chunks/./video.mp4-qFeNHvW30h7B8ZtqHmXWEgaYrc2r3gvTuyTGkcIU.part\" does not exist at /var/www/html/vendor/symfony/http-foundation/File/File.php:36)
[stacktrace]
#0 /var/www/html/vendor/symfony/http-foundation/File/UploadedFile.php(70): Symfony\\Component\\HttpFoundation\\File\\File->__construct()
#1 /var/www/html/vendor/pion/laravel-chunk-upload/src/Save/ChunkSave.php(230): Symfony\\Component\\HttpFoundation\\File\\UploadedFile->__construct()
#2 /var/www/html/vendor/pion/laravel-chunk-upload/src/Save/ParallelSave.php(145): Pion\\Laravel\\ChunkUpload\\Save\\ChunkSave->createFullChunkFile()
#3 /var/www/html/vendor/pion/laravel-chunk-upload/src/Save/ChunkSave.php(170): Pion\\Laravel\\ChunkUpload\\Save\\ParallelSave->buildFullFileFromChunks()
#4 /var/www/html/vendor/pion/laravel-chunk-upload/src/Save/ChunkSave.php(158): Pion\\Laravel\\ChunkUpload\\Save\\ChunkSave->tryToBuildFullFileFromChunks()
#5 /var/www/html/vendor/pion/laravel-chunk-upload/src/Save/ChunkSave.php(67): Pion\\Laravel\\ChunkUpload\\Save\\ChunkSave->handleChunk()
#6 /var/www/html/vendor/pion/laravel-chunk-upload/src/Save/ParallelSave.php(55): Pion\\Laravel\\ChunkUpload\\Save\\ChunkSave->__construct()
#7 /var/www/html/vendor/pion/laravel-chunk-upload/src/Handler/Traits/HandleParallelUploadTrait.php(30): Pion\\Laravel\\ChunkUpload\\Save\\ParallelSave->__construct()
#8 /var/www/html/vendor/pion/laravel-chunk-upload/src/Receiver/FileReceiver.php(100): Pion\\Laravel\\ChunkUpload\\Handler\\ResumableJSUploadHandler->startSaving()
#9 /var/www/html/app/Http/Controllers/Admin/UploadVideoController.php(77): Pion\\Laravel\\ChunkUpload\\Receiver\\FileReceiver->receive()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Admin\\UploadVideoController->store()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
```
